/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as EarnDioRouteImport } from './routes/earnDio'
import { Route as EssentialsRouteImport } from './routes/essentials'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PortalsRouteImport } from './routes/portals'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicDioAdPostbackRouteImport } from './routes/api/public/dio/ad-postback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnDioRoute = EarnDioRouteImport.update({
  id: '/earnDio',
  path: '/earnDio',
  getParentRoute: () => rootRouteImport,
} as any)
const EssentialsRoute = EssentialsRouteImport.update({
  id: '/essentials',
  path: '/essentials',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsRoute = PortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDioAdPostbackRoute = ApiPublicDioAdPostbackRouteImport.update({
  id: '/api/public/dio/ad-postback',
  path: '/api/public/dio/ad-postback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/dmca': typeof DmcaRoute
  '/earnDio': typeof EarnDioRoute
  '/essentials': typeof EssentialsRoute
  '/materials': typeof MaterialsRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/portals': typeof PortalsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/dio/ad-postback': typeof ApiPublicDioAdPostbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/dmca': typeof DmcaRoute
  '/earnDio': typeof EarnDioRoute
  '/essentials': typeof EssentialsRoute
  '/materials': typeof MaterialsRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/portals': typeof PortalsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/dio/ad-postback': typeof ApiPublicDioAdPostbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/dmca': typeof DmcaRoute
  '/earnDio': typeof EarnDioRoute
  '/essentials': typeof EssentialsRoute
  '/materials': typeof MaterialsRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/portals': typeof PortalsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/dio/ad-postback': typeof ApiPublicDioAdPostbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blocked'
    | '/dmca'
    | '/earnDio'
    | '/essentials'
    | '/materials'
    | '/mcp'
    | '/onboarding'
    | '/portals'
    | '/privacy'
    | '/profile'
    | '/support'
    | '/terms'
    | '/welcome'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/.lovable/oauth/consent'
    | '/api/public/dio/ad-postback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blocked'
    | '/dmca'
    | '/earnDio'
    | '/essentials'
    | '/materials'
    | '/mcp'
    | '/onboarding'
    | '/portals'
    | '/privacy'
    | '/profile'
    | '/support'
    | '/terms'
    | '/welcome'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/.lovable/oauth/consent'
    | '/api/public/dio/ad-postback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blocked'
    | '/dmca'
    | '/earnDio'
    | '/essentials'
    | '/materials'
    | '/mcp'
    | '/onboarding'
    | '/portals'
    | '/privacy'
    | '/profile'
    | '/support'
    | '/terms'
    | '/welcome'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/.lovable/oauth/consent'
    | '/api/public/dio/ad-postback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlockedRoute: typeof BlockedRoute
  DmcaRoute: typeof DmcaRoute
  EarnDioRoute: typeof EarnDioRoute
  EssentialsRoute: typeof EssentialsRoute
  MaterialsRoute: typeof MaterialsRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  PortalsRoute: typeof PortalsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicDioAdPostbackRoute: typeof ApiPublicDioAdPostbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnDio': {
      id: '/earnDio'
      path: '/earnDio'
      fullPath: '/earnDio'
      preLoaderRoute: typeof EarnDioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essentials': {
      id: '/essentials'
      path: '/essentials'
      fullPath: '/essentials'
      preLoaderRoute: typeof EssentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals': {
      id: '/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof PortalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dio/ad-postback': {
      id: '/api/public/dio/ad-postback'
      path: '/api/public/dio/ad-postback'
      fullPath: '/api/public/dio/ad-postback'
      preLoaderRoute: typeof ApiPublicDioAdPostbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlockedRoute: BlockedRoute,
  DmcaRoute: DmcaRoute,
  EarnDioRoute: EarnDioRoute,
  EssentialsRoute: EssentialsRoute,
  MaterialsRoute: MaterialsRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  PortalsRoute: PortalsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicDioAdPostbackRoute: ApiPublicDioAdPostbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
