// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { ensureFreshAccessToken } from './auth-token'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
//
// We forward a *fresh* access token. The server is stateless about auth (it only
// sees the access token, never the refresh token), so it cannot refresh on its
// own — if it received an expired token it would reject the call and the user
// would look logged out. `ensureFreshAccessToken()` refreshes first when needed
// (single-flight) and only returns null when there is genuinely no session.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const token = await ensureFreshAccessToken()
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
